# Generated by Django 5.1 on 2024-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=10)),
                ('contactNumber', models.IntegerField(max_length=11, unique=True)),
            ],
        ),
    ]
