# Generated by Django 5.1 on 2024-08-17 10:58

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactNumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number...', max_length=31),
        ),
    ]
